add getFelfId()
SignalK/signalk-js-client pull request #28
Opened 2017-08-15 21:09 UTC by e-sailing

Fix issues with self id which use the mmsi number by fetching the self id from the `/signalk/v1/self` endpoint.

2017-08-15 22:33 UTC, tkurki requested changes

2017-08-15 22:33 UTC, tkurki commented on index.js
> +Client.prototype.getSelf = function() {
This should be getSelfId, right?

2017-08-17 19:42 UTC, e-sailing commented
I thought it would be good to squach the changes to one commit. I test it with Sailgauge and Simplegauge.

2017-08-19 18:51 UTC, tkurki approved these changes

2017-08-19 18:51 UTC, merged